#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from itertools import product

def getLeetList(string):
    leet = ["Aa@",
            "Bb",
            "Cc",
            "Dd",
            "Ee",
            "Ff",
            "Gg",
            "Hh",
            "Ii1",
            "Jj",
            "Kk",
            "Ll1",
            "Mm",
            "Nn",
            "Oo0",
            "Pp",
            "Qq9",
            "Rr",
            "Ss$5",
            "Tt",
            "Uu",
            "Vv",
            "Ww",
            "Xx",
            "Yy",
            "Zz2"]
    getPlaces = lambda string: [leet[ord(el.upper()) - 65] for el in string]

    for letters in product(*getPlaces(string)):
        yield "".join(letters)

input_line = sys.stdin.readlines()
for line in input_line:
    for s in getLeetList(line.rstrip('\n')):
        print s
